var YouTube = [
[   {link:"https://www.youtube.com/embed/O5_s1OUizfQ",category:"sport"},
    {link:"https://www.youtube.com/embed/Kd-Va1m4s1E",category:"sport"},
    {link:"https://www.youtube.com/embed/dbsABwGERfY",category:"sport"},
    {link:"https://www.youtube.com/embed/UItWltVZZmE",category:"sport"},
    {link:"https://www.youtube.com/embed/49hYMvT10sg",category:"sport"},
    {link:"https://www.youtube.com/embed/m756Gz8de4M",category:"sport"},
    {link:"https://www.youtube.com/embed/QGm6v9-1ZBU",category:"sport"}  ],
    
[   {link:"https://www.youtube.com/embed/sBoVGqiSzr4",category:"hands-on"},
    {link:"https://www.youtube.com/embed/ifWqxuWyG88",category:"hands-on"},
    {link:"https://www.youtube.com/embed/FUeyrEN14Rk",category:"hands-on"},
    {link:"https://www.youtube.com/embed/FyC7pkT-dE0",category:"hands-on"},
    {link:"https://www.youtube.com/embed/b5-s_2ale1E",category:"hands-on"},
    {link:"https://www.youtube.com/embed/tCjFeHNPDQM",category:"hands-on"},
    {link:"https://www.youtube.com/embed/vHq3zcX-JWs",category:"hands-on"},
    {link:"https://www.youtube.com/embed/1OsV9Xe6h2M",category:"hands-on"},
    {link:"https://www.youtube.com/embed/nWJQvsZ6kT0",category:"hands-on"}  ],
    
[   {link:"https://www.youtube.com/embed/CuHrKkgyXhI",category:"arts"},
    {link:"https://www.youtube.com/embed/JVgYbq1DwT8",category:"arts"},
    {link:"https://www.youtube.com/embed/IpEuYp4_iSg",category:"arts"},
    {link:"https://www.youtube.com/embed/xv6w9mC33E8",category:"arts"},
    {link:"https://www.youtube.com/embed/B6-45rswo0o",category:"arts"}  ],
    
[   {link:"https://www.youtube.com/embed/gp2VvmUJJc8",category:"language"},
    {link:"https://www.youtube.com/embed/lSPOMKW8ivs",category:"language"},
    {link:"https://www.youtube.com/embed/Kz64czn1JcQ",category:"language"},
    {link:"https://www.youtube.com/embed/McZW0iDsZns",category:"language"},
    {link:"https://www.youtube.com/embed/23J4O8NvWBs",category:"language"},
    {link:"https://www.youtube.com/embed/9DdkqOHDiLE",category:"language"}  ],
    
[   {link:"https://www.youtube.com/embed/7Ron6MN45LY",category:"mind"},
    {link:"https://www.youtube.com/embed/ZF62fI3KK5s",category:"mind"},
    {link:"https://www.youtube.com/embed/xiTK523Ot5U",category:"mind"},
    {link:"https://www.youtube.com/embed/1UyJG2b8FMc",category:"mind"},
    {link:"https://www.youtube.com/embed/NAIQyoPcjNM",category:"mind"},
    {link:"https://www.youtube.com/embed/wCQSIub_g7M",category:"mind"}  ],
    
[   {link:"https://www.youtube.com/embed/OnUlRx3wKaQ",category:"house"},
    {link:"https://www.youtube.com/embed/vRtwq_XZEZM",category:"house"},
    {link:"https://www.youtube.com/embed/MSr04jhuTes",category:"house"},
    {link:"https://www.youtube.com/embed/2IBaaQXP39I",category:"house"},
    {link:"https://www.youtube.com/embed/HHgIC6YVQek",category:"house"},
    {link:"https://www.youtube.com/embed/R1FfZiiK-I4",category:"house"} ],
    
[   {link:"https://www.youtube.com/embed/liJWMwCX4nA",category:"NA"},
    {link:"https://www.youtube.com/embed/kCt1bmSASCI",category:"NA"},
    {link:"https://www.youtube.com/embed/epyQLWu0GZQ",category:"NA"},
    {link:"https://www.youtube.com/embed/rz4Dd1I_fX0",category:"NA"},
    {link:"https://www.youtube.com/embed/AtgfsRH3H3U",category:"NA"},
    {link:"https://www.youtube.com/embed/2tDg9BtM7g4",category:"NA"},
    {link:"https://www.youtube.com/embed/1jUpw1f64D0",category:"NA"},
    {link:"https://www.youtube.com/embed/5bHGLNB8sxQ",category:"NA"}    ],
]