var YouTube = [
[   {link:"https://www.youtube.com/embed/O5_s1OUizfQ",category:"sport"},
    {link:"https://www.youtube.com/embed/Kd-Va1m4s1E",category:"sport"},
    {link:"https://www.youtube.com/embed/dbsABwGERfY",category:"sport"},
    {link:"https://www.youtube.com/embed/UItWltVZZmE",category:"sport"},
    {link:"https://www.youtube.com/embed/49hYMvT10sg",category:"sport"},
    {link:"https://www.youtube.com/embed/m756Gz8de4M",category:"sport"},
    {link:"https://www.youtube.com/embed/QGm6v9-1ZBU",category:"sport"}  ],
    
[   {link:"https://www.youtube.com/embed/sBoVGqiSzr4",category:"hands-on"},
    {link:"https://www.youtube.com/embed/ifWqxuWyG88",category:"hands-on"},
    {link:"https://www.youtube.com/embed/FUeyrEN14Rk",category:"hands-on"},
    {link:"https://www.youtube.com/embed/FyC7pkT-dE0",category:"hands-on"},
    {link:"https://www.youtube.com/embed/b5-s_2ale1E",category:"hands-on"},
    {link:"https://www.youtube.com/embed/tCjFeHNPDQM",category:"hands-on"},
    {link:"https://www.youtube.com/embed/vHq3zcX-JWs",category:"hands-on"},
    {link:"https://www.youtube.com/embed/1OsV9Xe6h2M",category:"hands-on"},
    {link:"https://www.youtube.com/embed/nWJQvsZ6kT0",category:"hands-on"}  ],
    
[   {link:"https://www.youtube.com/embed/CuHrKkgyXhI",category:"arts"},
    {link:"https://www.youtube.com/embed/JVgYbq1DwT8",category:"arts"},
    {link:"https://www.youtube.com/embed/IpEuYp4_iSg",category:"arts"},
    {link:"https://www.youtube.com/embed/xv6w9mC33E8",category:"arts"},
    {link:"https://www.youtube.com/embed/B6-45rswo0o",category:"arts"}  ],
    
[   {link:"https://www.youtube.com/embed/gp2VvmUJJc8",category:"language"},
    {link:"https://www.youtube.com/embed/lSPOMKW8ivs",category:"language"},
    {link:"https://www.youtube.com/embed/Kz64czn1JcQ",category:"language"},
    {link:"https://www.youtube.com/embed/McZW0iDsZns",category:"language"},
    {link:"https://www.youtube.com/embed/9DdkqOHDiLE",category:"language"}  ],
    
[   {link:"https://www.youtube.com/embed/7Ron6MN45LY",category:"mind"},
    {link:"https://www.youtube.com/embed/ZF62fI3KK5s",category:"mind"},
    {link:"https://www.youtube.com/embed/xiTK523Ot5U",category:"mind"},
    {link:"https://www.youtube.com/embed/1UyJG2b8FMc",category:"mind"},
    {link:"https://www.youtube.com/embed/NAIQyoPcjNM",category:"mind"},
    {link:"https://www.youtube.com/embed/wCQSIub_g7M",category:"mind"},
    {link:"https://www.youtube.com/embed/r6sGWTCMz2k",category:"mind"} ],
    
[   {link:"https://www.youtube.com/embed/OnUlRx3wKaQ",category:"house"},
    {link:"https://www.youtube.com/embed/vRtwq_XZEZM",category:"house"},
    {link:"https://www.youtube.com/embed/MSr04jhuTes",category:"house"},
    {link:"https://www.youtube.com/embed/2IBaaQXP39I",category:"house"},
    {link:"https://www.youtube.com/embed/23J4O8NvWBs",category:"house"},
    {link:"https://www.youtube.com/embed/HHgIC6YVQek",category:"house"},
    {link:"https://www.youtube.com/embed/R1FfZiiK-I4",category:"house"} ],
    
[   {link:"https://www.youtube.com/embed/liJWMwCX4nA",category:"NA"},
    {link:"https://www.youtube.com/embed/kCt1bmSASCI",category:"NA"},
    {link:"https://www.youtube.com/embed/epyQLWu0GZQ",category:"NA"},
    {link:"https://www.youtube.com/embed/rz4Dd1I_fX0",category:"NA"},
    {link:"https://www.youtube.com/embed/AtgfsRH3H3U",category:"NA"},
    {link:"https://www.youtube.com/embed/2tDg9BtM7g4",category:"NA"},
    {link:"https://www.youtube.com/embed/1jUpw1f64D0",category:"NA"},
    {link:"https://www.youtube.com/embed/5bHGLNB8sxQ",category:"NA"},
    {link:"https://www.youtube.com/embed/S78s_DAh0Xc",category:"NA"},
    {link:"https://www.youtube.com/embed/VlYegmnCWIY",category:"NA"},
    {link:"https://www.youtube.com/embed/YiAFgpkzxEA",category:"NA"}    ],
]

var external = [
    [
        {title:"30 Moves to Make the Most of Your At-Home Workout",
        link:"https://www.healthline.com/health/fitness-exercise/at-home-workouts",
        category:"sport"},
        {title:"40 Ways to Exercise Without Realizing It",
        link:"https://www.nerdfitness.com/blog/25-ways-to-exercise-without-realizing-it/",
        category:"sport"},
        {title:"What sport are you made for?",
        link:"https://www.bbc.com/news/uk-28062001",
        category:"sport"},
        {title:"Unique Sports You Should Try as a Hobby",
        link:"https://thisladyblogs.com/4-unique-sports-you-should-try-as-a-hobby/",
        category:"sport"}
    ],
    [
        {title:"Pottery Tips for Beginners",
        link:"https://spinningpots.com/pottery-tips-beginners/",
        category:"hands-on"},
        {title:"Origami Ideas For All Occasions",
        link:"https://www.origamiway.com/origami-ideas.shtml",
        category:"hands-on"},
        {title:"Try Building Your Own PC",
        link:"https://www.wired.com/story/how-to-build-a-pc/",
        category:"hands-on"},
        {title:"Science Experiments Kids Can Do At Home",
        link:"https://www.weareteachers.com/easy-science-experiments/",
        category:"hands-on"},
        {title:"Cheap, & Easy DIY Robots",
        link:"https://blog.creationcrate.com/easy-at-home-diy-robot-projects/",
        category:"hands-on"}
    ],
    
    [
        {title:"How to Make a Collage",
        link:"https://www.wikihow.com/Make-a-Collage",
        category:"arts"},
        {title:"The arts",
        link:"https://en.wikipedia.org/wiki/The_arts",
        category:"arts"},
        {title:"Dos and Don’ts of Drawing Anatomy",
        link:"https://www.artistsnetwork.com/art-techniques/beginner-artist/drawing-anatomy-for-beginners/",
        category:"arts"},
        {title:"7 Major Painting Styles",
        link:"https://www.thoughtco.com/art-styles-explained-realism-to-abstract-2578625",
        category:"arts"},
        {title:"Basic Color Theory",
        link:"https://colormatters.com/color-and-design/basic-color-theory",
        category:"arts"},
        {title:"Drawing Ideas to Pursue Now",
        link:"https://homesthetics.net/drawing-ideas/",
        category:"arts"}
    ],
    [
        {title:"Learn Japanese!",
        link:"http://japanese-lesson.com/",
        category:"language"},
        {title:"Learn Russian!",
        link:"http://www.russianlessons.net/",
        category:"language"},
        {title:"Learn Italian!",
        link:"https://www.theitalianexperiment.com/learn-italian",
        category:"language"},
        {title:"Learn Latin!",
        link:"https://ancientlanguage.com/learn-latin/",
        category:"language"},
        {title:"Learn Egyptian!",
        link:"http://mylanguages.org/learn_egyptian.php",
        category:"language"}
    ],
    
    [
        {title:"Play and Learn Chess!",
        link:"https://www.chess.com/lessons",
        category:"mind"},
        {title:"Most Popular Programming Languages to Learn",
        link:"https://www.northeastern.edu/graduate/blog/most-popular-programming-languages/",
        category:"mind"},
        {title:"Interesting Facts About Computers",
        link:"https://www.incrediblelab.com/interesting-computer-facts/",
        category:"mind"},
        {title:"Mathematics",
        link:"https://en.wikipedia.org/wiki/Mathematics",
        category:"mind"},
        {title:"An important list of math formulas",
        link:"https://engineeringdiscoveries.com/most-important-list-of-math-formulas/",
        category:"mind"}
    ],
    
    [
        {title:"Painting Supplies Checklist",
        link:"https://www.realsimple.com/home-organizing/home-improvement/painting/painting-supplies-checklist",
        category:"house"},
        {title:"Best Ways to Kill Cockroaches",
        link:"https://www.familyhandyman.com/list/best-ways-to-kill-cockroaches/",
        category:"house"},
        {title:"How to Use a Washing Machine",
        link:"https://www.wikihow.com/Use-a-Washing-Machine",
        category:"house"},
        {title:"World's Best Lasagna",
        link:"https://www.allrecipes.com/recipe/23600/worlds-best-lasagna/",
        category:"house"},
        {title:"How to Sew",
        link:"https://www.wikihow.com/Sew",
        category:"house"}
    ],
    
    [
        {title:"A word from the American Red Cross",
        link:"https://www.redcross.org/about-us/news-and-events/news/2020/coronavirus-safety-and-readiness-tips-for-you.html",
        category:"NA"},
        {title:"Ways To Help Others During The Pandemic",
        link:"https://www.forbes.com/sites/forbesnonprofitcouncil/2020/11/10/generous-giving-prevails-ways-to-help-others-during-the-pandemic/?sh=205cd6762a22",
        category:"NA"},
        {title:"More Ways to Help Others During the Coronavirus Pandemic",
        link:"https://www.idealist.org/en/careers/help-others-coronavirus",
        category:"NA"},
        {title:"Coronavirus Pevention Tips",
        link:"https://www.webmd.com/lung/coronavirus-prevention-overview#1",
        category:"NA"},
        {title:"Corona Live",
        link:"https://www.worldometers.info/coronavirus/",
        category:"NA"}
    ]
]