var YouTube = [
[   {link:"https://www.youtube.com/embed/O5_s1OUizfQ",category:"sport"},
    {link:"https://www.youtube.com/embed/Kd-Va1m4s1E",category:"sport"},
    {link:"https://www.youtube.com/embed/dbsABwGERfY",category:"sport"},
    {link:"https://www.youtube.com/embed/UItWltVZZmE",category:"sport"},
    {link:"https://www.youtube.com/embed/49hYMvT10sg",category:"sport"},
    {link:"https://www.youtube.com/embed/m756Gz8de4M",category:"sport"},
    {link:"https://www.youtube.com/embed/QGm6v9-1ZBU",category:"sport"}  ],
    
[   {link:"https://www.youtube.com/embed/sBoVGqiSzr4",category:"hands-on"},
    {link:"https://www.youtube.com/embed/ifWqxuWyG88",category:"hands-on"},
    {link:"https://www.youtube.com/embed/FUeyrEN14Rk",category:"hands-on"},
    {link:"https://www.youtube.com/embed/FyC7pkT-dE0",category:"hands-on"},
    {link:"https://www.youtube.com/embed/b5-s_2ale1E",category:"hands-on"},
    {link:"https://www.youtube.com/embed/tCjFeHNPDQM",category:"hands-on"},
    {link:"https://www.youtube.com/embed/vHq3zcX-JWs",category:"hands-on"},
    {link:"https://www.youtube.com/embed/1OsV9Xe6h2M",category:"hands-on"},
    {link:"https://www.youtube.com/embed/nWJQvsZ6kT0",category:"hands-on"}  ],
    
[   {link:"https://www.youtube.com/embed/CuHrKkgyXhI",category:"arts"},
    {link:"https://www.youtube.com/embed/JVgYbq1DwT8",category:"arts"},
    {link:"https://www.youtube.com/embed/IpEuYp4_iSg",category:"arts"},
    {link:"https://www.youtube.com/embed/xv6w9mC33E8",category:"arts"},
    {link:"https://www.youtube.com/embed/B6-45rswo0o",category:"arts"},
    {link:"https://www.youtube.com/embed/827jmswqnEA",category:"arts"},
    {link:"https://www.youtube.com/embed/BBz-Jyr23M4",category:"arts"},
    {link:"https://www.youtube.com/embed/88G0O5unNuQ",category:"arts"}],
    
[   {link:"https://www.youtube.com/embed/gp2VvmUJJc8",category:"language"},
    {link:"https://www.youtube.com/embed/lSPOMKW8ivs",category:"language"},
    {link:"https://www.youtube.com/embed/Kz64czn1JcQ",category:"language"},
    {link:"https://www.youtube.com/embed/McZW0iDsZns",category:"language"},
    {link:"https://www.youtube.com/embed/9DdkqOHDiLE",category:"language"},
    {link:"https://www.youtube.com/embed/dKG68y2VC0Y",category:"language"},
    {link:"https://www.youtube.com/embed/Dv2rFqmI1_k",category:"language"},
    {link:"https://www.youtube.com/embed/McZW0iDsZns",category:"language"},
    {link:"https://www.youtube.com/embed/LGMKg6MUdxI",category:"language"}],
    
[   {link:"https://www.youtube.com/embed/7Ron6MN45LY",category:"mind"},
    {link:"https://www.youtube.com/embed/ZF62fI3KK5s",category:"mind"},
    {link:"https://www.youtube.com/embed/xiTK523Ot5U",category:"mind"},
    {link:"https://www.youtube.com/embed/1UyJG2b8FMc",category:"mind"},
    {link:"https://www.youtube.com/embed/NAIQyoPcjNM",category:"mind"},
    {link:"https://www.youtube.com/embed/wCQSIub_g7M",category:"mind"},
    {link:"https://www.youtube.com/embed/r6sGWTCMz2k",category:"mind"},
    {link:"https://www.youtube.com/embed/ovJcsL7vyrk",category:"mind"}],
    
[   {link:"https://www.youtube.com/embed/OnUlRx3wKaQ",category:"house"},
    {link:"https://www.youtube.com/embed/vRtwq_XZEZM",category:"house"},
    {link:"https://www.youtube.com/embed/MSr04jhuTes",category:"house"},
    {link:"https://www.youtube.com/embed/2IBaaQXP39I",category:"house"},
    {link:"https://www.youtube.com/embed/23J4O8NvWBs",category:"house"},
    {link:"https://www.youtube.com/embed/HHgIC6YVQek",category:"house"},
    {link:"https://www.youtube.com/embed/R1FfZiiK-I4",category:"house"},
    {link:"https://www.youtube.com/embed/1eL7llVPuJg",category:"house"}],
    
[   {link:"https://www.youtube.com/embed/liJWMwCX4nA",category:"NA"},
    {link:"https://www.youtube.com/embed/kCt1bmSASCI",category:"NA"},
    {link:"https://www.youtube.com/embed/epyQLWu0GZQ",category:"NA"},
    {link:"https://www.youtube.com/embed/rz4Dd1I_fX0",category:"NA"},
    {link:"https://www.youtube.com/embed/AtgfsRH3H3U",category:"NA"},
    {link:"https://www.youtube.com/embed/2tDg9BtM7g4",category:"NA"},
    {link:"https://www.youtube.com/embed/1jUpw1f64D0",category:"NA"},
    {link:"https://www.youtube.com/embed/5bHGLNB8sxQ",category:"NA"},
    {link:"https://www.youtube.com/embed/S78s_DAh0Xc",category:"NA"},
    {link:"https://www.youtube.com/embed/VlYegmnCWIY",category:"NA"},
    {link:"https://www.youtube.com/embed/YiAFgpkzxEA",category:"NA"}    ],
]

var external = [
        [
            "Go for a short run around the table",
            "Search for Just Dance videos and have fun!",
            "Make a salad using only green fruits and vegetable",
            "Buy a doctor some cofee",
            "10 PUSH-UPS NOW!",
            "10 SIT-UPS NOW!",
            "Try to clap your hands as fast as possible, (the world record is 1080 claps in one minute)",
            "Eat an apple, if you don't have an apple, go buy some, keeps the doctor away",
            "Dive into the incredible sport of cup stacking",
            "Check your pulse, you may never know...",
            
        ],
    
    [
        "Make a flower origami",
        "Look at computer building videos, because we know you can't afford one",
        "Paint a T-shirt",
        "Make Soap Balloons",
        "Make a bird feeder",
        "Build a fort",
        "Press some flower",
        "Make a ginger bread house, (or something similar)",
        "Make a 3D happy birthhday card",
        "Make a tic-tac-toe game with pebbles",
        "Make little christmas trees out of pine cones",
        "Made a photo album! (a physical one)"
    ],
    
    [
        "Draw a butterfly with a skull",
        "Trow some paint on a piece of paper to pretend you're Jackson Pollock",
        "Paint empty plastic bottles",
        "Write a poem!",
        "Write a haiku!",
        "Write an acrostic of your name",
        "Write an acrostic of the alphabet",
        "Write a letter for someone.",
        "Write a journal page, you need it",
        "Watch every Eurovision winner",
        "Dye your hair",
        "Watch '12 Angry Men' ",
        "Watch the movie 'Shutter Island' "
    ],
    
    [
        "Say it three times fast: Eleven benevolent elephants.",
        "Say it three times fast: She sees cheese.",
        "Say it three times fast: Truly rural.",
        "Say it three times fast: Cooks cook cupcakes quickly.",
        "Say it three times fast: Fuzzy Wuzzy was a bear. Fuzzy Wuzzy had no hair. Fuzzy Wuzzy wasn’t very fuzzy, was he?",
        "Say it three times fast: Specific Pacific.",
        "Say it one time fast: Betty Botter bought some butter but, said she, the butter’s bitter.<br/> If I put it in my batter, it will make my batter bitter.<br/> But a bit of better butter will make my bitter batter better.<br/> So she bought some better butter, better than the bitter butter, put it in her bitter batter, made her bitter batter better.<br/> So ‘t was better Betty Botter bought some better butter.",
        "Translate it into Armenian: My dog has a blue pillow",
        "Translate it into French: The ripe blackberry murmurs at the wall",
        "Translate it into Japanese: coffee, internet, soup, panties.",
        "Translate it into Bosnian: rbhtttpftttbhtbhtpftttbhtttpftttbhtbhtpfbhtcbhttt<br/>pftttbhtbhtpftttbhtttpftttbhtbhtpfbhtcbhtttpfttt<br/>bhtbhtpftttbhtttpftttbhtbhtpfbhtcbhtttpftttbhtbhtp<br/>ftttbhtttpftttbhtbhtpfbhtc",
        "Read a book!",
        "Read a poem!"
    ],
    
    [
        "Take a personality test on https://www.16personalities.com/",
        "Visit a museum <br/>(you can also do this online https://www.travelandleisure.com/attractions<br/>/museums-galleries/museums-with-virtual-tours)",
        "Watch a VSauce video!",
        "Play a game of chess!",
        "Learn about Stoicism!",
        "Meditate!",
        "Play sudoku!"
    ],
    [
        "Rearrange furniture",
        "Build a card castle",
        "Decorate your walls",
        "Clean your room",
        "Clean your wardrobe",
        "Clean your fridge",
        "Clean the toilet",
        "Cook some pasta",
        "Cook potato chips!",
        "Try a new laundry folding technique",
        "Cook a chicken breast with your smoothing iron"
    ],
    [
        "Post a photo on social media showcasing how you manage to spend all day at home",
        "Hug someone... virtually",
        "Call an old friend, ad cheer them up during this pandemic",
        "Dress up like it's a business meeting",
        "Let your friend (which is not in the same building as you) order pizza for you",
        "Buy a busy doctor some coffee"
    ]   
]


var jokes=[
    {setup:"The World Health Organization announced that dogs cannot contract COVID-19. Dogs previously held in quarantine can now be released.",punchline:"To be clear, WHO let the dogs out."},
    {setup:"Since we’re all in quarantine I guess we’ll be making only inside jokes from now on.",punchline:""},
    {setup:"What’s the difference between COVID-19 and Romeo and Juliet?",punchline:"One’s the coronavirus and the other is a Verona crisis."},
    {setup:"Finland just closed its borders. You know what that means.",punchline:"No one will be crossing the finish line."},
    {setup:"So many coronavirus jokes out there, it’s a pundemic.",punchline:""},
    {setup:"What did the man say to the bartender?",punchline:"I’ll have a corona, hold the virus."},
    {setup:"Today's Weather: Room Temperature.",punchline:""},
    {setup:"Anyone else's car getting three weeks to the gallon?",punchline:""},
    {setup:"Never in my life would I imagine... ",punchline:"that my hands would consume more alcohol than my mouth"},
    {setup:"My mom always told me I wouldn’t accomplish anything by lying in bed all day.",punchline:"But look at me now, ma! I’m saving the world!"},
    {setup:"After years of wanting to thoroughly clean my house but lacking the time. ",punchline:"This week I discovered that wasn’t the reason."},
    {setup:"Being quarantined with a talkative child... ",punchline:"is like having an insane parrot glued to your shoulder"},
    {setup:"I’m not talking to myself...",punchline:"I’m having a parent-teacher conference."},
    {setup:"I finished Netflix today.",punchline:""},
    {setup:"Pollen still coming out during a global pandemic?",punchline:"Bitch read the room."},
    {setup:"Day 121 at home and the dog is looking at me like:",punchline:"“See? This is why I chew the furniture!”"},
    {setup:"Why do they call it the novel coronavirus?",punchline:"It’s a long story…."},
    {setup:"What should you do if you don’t understand a coronavirus joke?",punchline:"Be patient."},
    {setup:"Yeah, I have plans tonight. ",punchline:"I’ll probably hit the living room around 8 or 9."},
    {setup:"You know what they say:",punchline:"feed a cold, starve a fever, drink a corona."},
    {setup:"What did the sick parent make their kids for lunch? ",punchline:"Mac and sneeze."},
    {setup:"Where do sick boats go to get healthy? ",punchline:"The dock!"},
    {setup:"Back in my day, you would cough to cover up a fart.",punchline:"Now, with COVID-19, you fart to cover up a cough."},
    {setup:"Why don’t chefs find coronavirus jokes funny?",punchline:"They’re in bad taste."},
    {setup:"I’ll tell you a coronavirus joke now...",punchline:"but you’ll have to wait two weeks to see if you got it."},
    {setup:"What do you tell yourself when you wake up late for work and realize you have a fever?",punchline:"Self, I so late."},
    {setup:"If there’s a baby boom nine months from now...",punchline:"what will happen in 2033? "},
    {setup:"There will be a whole bunch of quaranteens",punchline:""},
    {setup:"Did you hear the joke about the germ?",punchline:"Never mind, I don’t want to spread it around."},
    {setup:"Why didn’t the sick guy get the joke? ",punchline:"It flu over his head."},
    {setup:"What do you call panic-buying of sausage and cheese in Germany? ",punchline:"The wurst-kase scenario."},
    {setup:"Nail salons, hair salons, waxing center and tanning places are closed.",punchline:"It’s about to get ugly out there."} 
    
]